# .circleci/config.yml

# Specify the config version - version 2.1 is latest.
version: 2.1

# Define the jobs for the current project.
jobs:
  build-and-test:
    # Specify the Xcode version to use.
    macos:
      xcode: "11.3.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    # Define the steps required to build the project.
    steps:
      # Get the code from the VCS provider.
      - checkout

      # Download CocoaPods specs via HTTPS (faster than Git)
      # and install CocoaPods.
      - run:
          name: pipefail
          command: set -o pipefail

      - run:
          name: version
          command: xcodebuild -version

      - run:
          name: sdks
          command: xcodebuild -showsdks

      - run:
          name: devices
          command: instruments -s devices

      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 11 Pro (13.3) [" || true

      - run:
          name: Run tests
          command: xcodebuild -workspace AutoGraph.xcworkspace -scheme AutoGraph -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' ONLY_ACTIVE_ARCH=NO build test

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

workflows:
  version: 2
  build-test-lint:
    jobs:
      - swiftlint
      - build-and-test
